title: Welcome to Meta Innovation!
description: Meta Innovation is an AI startup company that creates various innovative AI apps, websites, serving clients worldwide.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
